server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhihu?useUnicode=true&characterEncoding=utf8
    username: root
    password: 971003
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
mybatis:
  mapper-locations: classpath:/mappers/*.xml
